version: 2
jobs:
  build:
    working_directory: /go/src/github.com/CityOfZion/neo-go
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Revision }}
      - run: BUILD=false /scripts/build.sh
      - save_cache:
          key: dependency-cache-{{ .Revision }}
          paths:
            - vendor
  test:
    working_directory: /go/src/github.com/CityOfZion/neo-go
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Revision }}
      - run: make test
  vet:
    working_directory: /go/src/github.com/CityOfZion/neo-go
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Revision }}
      - run: make vet
  check_version:
    working_directory: /go/src/github.com/CityOfZion/neo-go
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - run: make check-version

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master
      - test:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master
      - vet:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master
      - check_version:
          filters:
            branches:
              ignore: master